### ISSUE TITLE
Patch progress checklist

### ISSUE THREAD

**Issue by ooa113y** [ooa113y/umineko-catbox-english#3]
This issue is here to keep track of current progress of the patch in a more detailed fashion. It will be closed when the patch is "done".

- [x] SNR edits (translating and testing the actual script)
  - [x] Episode 1
  - [x] Episode 2
  - [x] Episode 3
  - [x] Episode 4
  - [x] Episode 5
  - [x] Episode 6
  - [x] Episode 7
  - [x] Episode 8
  - [x] Tsubasa
    - [x] Story01
    - [x] Story02
    - [x] Story03
    - [x] Story04
    - [x] Story05
    - [x] Story06
    - [x] Story07
    - [x] Story08
    - [x] Story09
    - [x] Story10
    - [x] Story11
    - [x] Story12
    - [x] Story13
    - [x] Story14
    - [x] Story15
    - [x] Story16
    - [x] Story17
    - [x] Story18
    - [x] Story19
    - [x] Story20
  - [x] Hane
    - [x] Story01
    - [x] Story02
  - [x] Saku
    - [x] Story01
    - [x] Story02
  - [x] Tips
  - [x] Character descriptions
  - [x] Song titles
  - [x] Chapter titles
- [x] Background editing (need to change backgrounds that have text to English)
  - [x] Main episodes
  - [x] Tsubasa
  - [x] Hane
  - [x] Saku
- [x] Texture editing (need to modify textures to have English text on them)
  - [x] `murderer.txa`
  - [x] `last.txa`
  - [x] `snrsel.txa`
  - [x] `quiz.txa`
  - [x] `bgmmode.txa`
  - [x] `adv.txa`
  - [x] `bupmode.txa`
  - [x] `cgmode.txa`
  - [x] `chars.txa`
  - [x] `tips.txa`
  - [x] `config.txa`
  - [x] `logview.txa`
  - [x] `moviemode.txa`
  - [x] `saveload.txa`
  - [x] `title.txa`
 - [x] exefs editing (need to change hardcoded strings)
   - [x] UI-related text (save prompts etc)
   - [x] Murderer-related text

**Comment by depesruts** [comment]
I read the VN with this patch in my switch a month ago and I've been following the github since then, thank you and congratulations on the release!!

**Comment by beato91** [comment]
i signed up an account just to thank you!
great job!
tho i have one question if you don't mind: when i first came across this patch very recently i noticed it hasn't been updated in slightly more than 2 months, but thankfully there was an update today (at the day of this comment) so i was wondering if you have a tentative ETA of sorts.

**Comment by beato91** [comment]
thank you very much!
i have a question if you don't mind: any tentative ETA of sorts?

**Comment by ooa113y** [comment]
> thank you very much! i have a question if you don't mind: any tentative ETA of sorts?

No, sorry. I only work on this in my free time and when I have the energy to, and I'm not sure how long it will take. As you can see, the patch is kind of close to completion now that I'm around halfway through Tsubasa, but I do not really have a consistent pace working on this stuff -- my energy is limited and not exactly predictable. It will be finished when it is.

Of course, you can already play through the existing content, so if you're intending to start Umineko now, you should feel free to go ahead and just update the patch when it's done.

**Comment by beato91** [comment]
as seen in nasuverse VNs, only fans can keep a series truly alive and make it infinitely better. bless you :)

**Comment by AsianInsomniac** [comment]
Fantastic job on this mod!
Though I would just like to ask if there's a way to change the dialogue font since the default one looks way too big.

**Comment by ooa113y** [comment]
The font can be theoretically replaced (though it will break some manually-aligned lines in the script), but it won't actually make it any smaller since the font size and the font face aren't dependent on each other.  There is a fairly obvious reason the font is "way too big", though -- this is a console game, meant to be playable on a TV that's far away from your face, and since "playing" it is basically just reading a wall of text, they aimed for a comfortable experience there. If you are experiencing it on an emulator, it may feel "off" since PC VNs, especially English ones, generally use smaller fonts to fit more text on screen at once.
